<?php

namespace Tests\Feature\Domains\Auth\Http\Controllers\Backend\Role;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Domains\Auth\Http\Controllers\Backend\Role\RoleController
 */
class RoleControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin.auth.role.create'));

        $response->assertOk();
        $response->assertViewIs();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->delete(route('admin.auth.role.destroy', ['role' => $role]));

        $response->assertRedirect(withFlashSuccess(__('The role was successfully deleted.')));
        $this->assertDeleted($admin);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Domains\Auth\Http\Controllers\Backend\Role\RoleController::class,
            'destroy',
            \App\Domains\Auth\Http\Requests\Backend\Role\DeleteRoleRequest::class
        );
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin.auth.role.edit', ['role' => $role]));

        $response->assertOk();
        $response->assertViewIs();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Domains\Auth\Http\Controllers\Backend\Role\RoleController::class,
            'edit',
            \App\Domains\Auth\Http\Requests\Backend\Role\EditRoleRequest::class
        );
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin.auth.role.index'));

        $response->assertOk();
        $response->assertViewIs('backend.auth.role.index');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('admin.auth.role.store'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(withFlashSuccess(__('The role was successfully created.')));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Domains\Auth\Http\Controllers\Backend\Role\RoleController::class,
            'store',
            \App\Domains\Auth\Http\Requests\Backend\Role\StoreRoleRequest::class
        );
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->patch(route('admin.auth.role.update', ['role' => $role]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(withFlashSuccess(__('The role was successfully updated.')));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Domains\Auth\Http\Controllers\Backend\Role\RoleController::class,
            'update',
            \App\Domains\Auth\Http\Requests\Backend\Role\UpdateRoleRequest::class
        );
    }

    // test cases...
}
