<?php

namespace Tests\Feature\Domains\Auth\Http\Controllers\Frontend\User;

use Tests\TestCase;

/**
 * @see \App\Domains\Auth\Http\Controllers\Frontend\User\DashboardController
 */
class DashboardControllerTest extends TestCase
{
    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('frontend.user.dashboard'));

        $response->assertOk();
        $response->assertViewIs('frontend.user.dashboard');

        // TODO: perform additional assertions
    }

    // test cases...
}
