<?php

namespace Tests\Feature\Domains\Auth\Http\Controllers\Frontend\User;

use Tests\TestCase;

/**
 * @see \App\Domains\Auth\Http\Controllers\Frontend\User\ProfileController
 */
class ProfileControllerTest extends TestCase
{
    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->patch(route('frontend.user.profile.update'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(withFlashInfo(__('You must confirm your new e-mail address before you can go any further.')));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Domains\Auth\Http\Controllers\Frontend\User\ProfileController::class,
            'update',
            \App\Domains\Auth\Http\Requests\Frontend\User\UpdateProfileRequest::class
        );
    }

    // test cases...
}
