<?php

namespace Tests\Feature\Domains\Auth\Http\Controllers\Frontend;

use Tests\TestCase;

/**
 * @see \App\Domains\Auth\Http\Controllers\Frontend\HomeController
 */
class HomeControllerTest extends TestCase
{
    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('frontend.index'));

        $response->assertOk();
        $response->assertViewIs('frontend.index');

        // TODO: perform additional assertions
    }

    // test cases...
}
