<?php

namespace Tests\Feature\Domains\Auth\Http\Controllers\Backend\User;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Domains\Auth\Http\Controllers\Backend\User\DeactivatedUserController
 */
class DeactivatedUserControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin.auth.user.deactivated'));

        $response->assertOk();
        $response->assertViewIs('backend.auth.user.deactivated');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin.auth.user.mark', ['user' => $user, 'status' => $status]));

        $response->assertRedirect(withFlashSuccess(__('The user was successfully updated.')));

        // TODO: perform additional assertions
    }

    // test cases...
}
