<?php

namespace Tests\Feature\Domains\Auth\Http\Controllers\Backend\User;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Domains\Auth\Http\Controllers\Backend\User\UserPasswordController
 */
class UserPasswordControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin.auth.user.change-password', ['user' => $user]));

        $response->assertOk();
        $response->assertViewIs();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Domains\Auth\Http\Controllers\Backend\User\UserPasswordController::class,
            'edit',
            \App\Domains\Auth\Http\Requests\Backend\User\EditUserPasswordRequest::class
        );
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->patch(route('admin.auth.user.change-password.update', ['user' => $user]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(withFlashSuccess(__('The user\'s password was successfully updated.')));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Domains\Auth\Http\Controllers\Backend\User\UserPasswordController::class,
            'update',
            \App\Domains\Auth\Http\Requests\Backend\User\UpdateUserPasswordRequest::class
        );
    }

    // test cases...
}
