<?php

namespace Tests\Feature\Domains\Auth\Http\Controllers\Backend\User;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Domains\Auth\Http\Controllers\Backend\User\UserSessionController
 */
class UserSessionControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin.auth.user.clear-session', ['user' => $user]));

        $response->assertRedirect(withFlashSuccess(__('The user\'s session was successfully cleared.')));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Domains\Auth\Http\Controllers\Backend\User\UserSessionController::class,
            'update',
            \App\Domains\Auth\Http\Requests\Backend\User\ClearUserSessionRequest::class
        );
    }

    // test cases...
}
