<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\LocaleController
 */
class LocaleControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function change_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('locale.change', ['lang' => $lang]));

        $response->assertRedirect(back());

        // TODO: perform additional assertions
    }

    // test cases...
}
