<?php

namespace Tests\Feature\Domains\Auth\Http\Controllers\Frontend\Auth;

use Tests\TestCase;

/**
 * @see \App\Domains\Auth\Http\Controllers\Frontend\Auth\ConfirmPasswordController
 */
class ConfirmPasswordControllerTest extends TestCase
{
    /**
     * @test
     */
    public function confirm_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('frontend.auth.'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_confirm_form_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('frontend.auth.password.confirm'));

        $response->assertOk();
        $response->assertViewIs('frontend.auth.passwords.confirm');

        // TODO: perform additional assertions
    }

    // test cases...
}
