<?php

namespace Tests\Feature\Domains\Auth\Http\Controllers\Frontend\Auth;

use Tests\TestCase;

/**
 * @see \App\Domains\Auth\Http\Controllers\Frontend\Auth\DisableTwoFactorAuthenticationController
 */
class DisableTwoFactorAuthenticationControllerTest extends TestCase
{
    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->delete(route('frontend.user.account.2fa.destroy'));

        $response->assertRedirect(withFlashSuccess(__('Two Factor Authentication Successfully Disabled')));
        $this->assertDeleted($frontend);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Domains\Auth\Http\Controllers\Frontend\Auth\DisableTwoFactorAuthenticationController::class,
            'destroy',
            \App\Domains\Auth\Http\Requests\Frontend\Auth\DisableTwoFactorAuthenticationRequest::class
        );
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('frontend.user.account.2fa.disable'));

        $response->assertOk();
        $response->assertViewIs('frontend.user.account.tabs.two-factor-authentication.disable');

        // TODO: perform additional assertions
    }

    // test cases...
}
