<?php

namespace Tests\Feature\Domains\Auth\Http\Controllers\Frontend\Auth;

use Tests\TestCase;

/**
 * @see \App\Domains\Auth\Http\Controllers\Frontend\Auth\LoginController
 */
class LoginControllerTest extends TestCase
{
    /**
     * @test
     */
    public function login_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('frontend.auth.'), [
            // TODO: send request data
        ]);

        $response->assertOk();
        $response->assertViewIs('frontend.auth.login');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function logout_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('frontend.auth.logout'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_login_form_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('frontend.auth.login'));

        $response->assertOk();
        $response->assertViewIs('frontend.auth.login');

        // TODO: perform additional assertions
    }

    // test cases...
}
