<?php

namespace Tests\Feature\Domains\Auth\Http\Controllers\Frontend\Auth;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Domains\Auth\Http\Controllers\Frontend\Auth\SocialController
 */
class SocialControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function callback_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('frontend.auth.', ['provider' => $provider]));

        $response->assertRedirect(withFlashDanger(__('Your account has been deactivated.')));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function redirect_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('frontend.auth.social.login', ['provider' => $provider]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
